### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Preservation-Quest**

### CODE REVIEW

**Comment by Preservation-Quest** [comment]
Added numbering to the steps in the Ubuntu installation guide.

**Comment by ivan** [comment]
I think numbering this would be fine, but the sections at each numbered step would have to be indented, as in other parts of the README.

**Comment by Preservation-Quest** [comment]
> I think numbering this would be fine, but the sections at each numbered step would have to be indented, as in other parts of the README.

Same spacing as used in the other installation sections was applied.

**Comment by ivan** [comment]
Please see the indentation in the following section `Install on another distribution lacking Python 3.7.x` for how to number things and have the entire step be properly indented.

**Comment by Preservation-Quest** [comment]
Done.

**Comment by ivan** [comment]
Thanks! I committed your commit, though I have to push the Close button here.

**Pull request closed without merging**
